[styles.battery]
high_battery_color = "#a6da95"
low_battery_color = "#ed8796"
medium_battery_color = "#eed49f"

[styles.cpu]
all_entry_color = "#f4dbd6"
avg_entry_color = "#ee99a0"
cpu_core_colors = [
    "#ed8796",
    "#f5a97f",
    "#eed49f",
    "#a6da95",
    "#7dc4e4",
    "#c6a0f6",
]

[styles.graphs]
graph_color = "#a5adcb"

[styles.graphs.legend_text]
color = "#a5adcb"

[styles.memory]
arc_color = "#91d7e3"
cache_color = "#ed8796"
gpu_colors = [
    "#7dc4e4",
    "#c6a0f6",
    "#ed8796",
    "#f5a97f",
    "#eed49f",
    "#a6da95",
]
ram_color = "#a6da95"
swap_color = "#f5a97f"

[styles.network]
rx_color = "#a6da95"
rx_total_color = "#91d7e3"
tx_color = "#ed8796"
tx_total_color = "#a6da95"

[styles.tables.headers]
color = "#f4dbd6"

[styles.widgets]
border_color = "#5b6078"
selected_border_color = "#f5bde6"

[styles.widgets.disabled_text]
color = "#24273a"

[styles.widgets.selected_text]
bg_color = "#c6a0f6"
color = "#181926"

[styles.widgets.text]
color = "#cad3f5"

[styles.widgets.widget_title]
color = "#f0c6c6"
